#define ROOM "/d/newbie/gnome/rooms/"
#define UNDER "/d/newbie/gnome/tunnels/"
#define MISC "/d/newbie/gnome/items/"
#define ARMOR "/d/newbie/gnome/armour/"
#define WEAPON "/d/newbie/gnome/weapons/"
#define STOCK "/d/newbie/gnome/buildings/"
#define CHAR "/d/newbie/gnome/npcs/"
