#define CAVE1 "/d/newbie/grads/rooms/cave1"
#define VALLEY "/d/newbie/grads/rooms/valley/"
#define WEAPON "/d/newbie/drow/weapons/"
#define ARMOUR "/d/newbie/drow/armour/"
#define CHAR "/d/newbie/grads/npcs/"
