#define MAZE "/d/newbie/drow/maze/"
#define WEAPON "/d/newbie/drow/weapons/"
#define ARMOUR "/d/newbie/drow/armour/"
#define CHAR "/d/newbie/drow/mobs/"
#define ARM "/baseobs/armours/"
#define OBJ "/baseobs/weapons/"
#define ITEM "/d/newbie/drow/items/"
