/*  Neutral Evil...  Should be a dark place but halfway in between Lawful
    and Chaotic.  We'll try for hot but not unbearably so, maybe some
    Chaotic aspects with a little Law balanced in there...
    We'll see how it goes.

    Guilo                              [The Bearded One]
*/

inherit "/std/sacroom";

void setup() {

   set_light(30);
  add_property("no_clean_up",1);

   set_short("The Cathedral of Neutral Evil");

   set_long("\nThe Cathedral of Neutral Evil:  Mosque of Balanced Hatred\n\n"
            "   Your eyes slowly adjust to the nearly impenetrable "
            "darkness that pervades this cavern.  After a time you begin "
            "to notice that there is light here.  It filters up from molten "
            "rivers of magma spread throughout the cavern like the fingers "
            "of some ancient evil reaching out to grasp and destroy.  Soot "
            "swirls around you making it hard to breathe properly, adding "
            "to the darkness.  The cavern must be huge but it is hard to "
            "determine as both sound and light are absorbed with the same "
            "voracious appetite.  Evil voices whisper into your mind words "
            "of hatred and destruction.  Seductive but somehow jumbled you "
            "find it difficult to understand what they are saying.  The "
            "heat from the lava flows rises steadily through the gloom as "
            "sweat pours from your body in a vain attempt to cool itself.  "
            "In the heart of this twisted shrine of evil stands an altar "
            "glowing with a power and a will all its own.  You approach "
            "slowly and cautiously, afraid that you may anger the "
            "forces at work here.\n"
            "\n");

   add_item(({"darkness"}),
            "   The darkness envelopes and devours both sound and light.  "
            "Momentarily at bay from the light generated by the magma flows, "
            "it waits for the light to die out ... as it surely must.  The "
            "darkness is patient, and endless.  It waits.\n"
            "\n");

   add_item(({"light"}),
            "   The light from the magma flows creates a dim red glow that "
            "pushes the darkness aside for a time.  The red glow off the "
            "obsidian rock of this cavern creates errie and bizzare images "
            "to dance and jump about the cavern.  You feel as though you "
            "are in a room filled with hundreds of creatures, each wandering "
            "seemingly without purpose and yet somehow driven to an unseen "
            "goal.\n"
            "\n");

   add_item(({"magma","river","rivers","magma flows","flows"}),
            "   The magma flows glow with a red hot light and cut their "
            "way through the cavern in seemingly random paths.  You can't "
            "help but get the feeling that they are following a pattern of "
            "some kind.  Cutting an image or a purpose into the cavern "
            "floor.  Like fingers of some ancient evil they reach out to "
            "devour and destroy.\n"
            "\n");

   add_item(({"cavern"}),
            "   The cavern is dark and warm.  Evil moves and dances in the "
            "reflections from the magma flows.  The floor and walls, what "
            "little of them you can actually see, are made from the purest "
            "of obsidian.  The rock, in combination with the soot and the "
            "darkness, seems to absorb light and life alike.\n"
            "\n");

   add_item(({"soot"}),
            "   The soot rises from the burning rock in the magma flows and "
            "seems to clog your nose and throat.  You cough and gasp for air "
            "but nothing seems to help.  Your eyes burn from the dark air.\n"
            "\n");

   add_sound(({"voices","evil voices"}),
             "  The whispering of the voices seems jumbled and confused.  "
             "You notice that you can -feel- rather than hear them.  Hatred "
             "and destructive thoughts are driven into your mind.  You try "
             "to shut out the sounds but they are incessant and endless.\n"
             "\n");

   add_feel(({"heat"}),
            "   The heat is penetrating and hammering but not completely "
            "unbearable.  It rises from the floor in waves that distort your "
            "vision and drives water from your body.  You can feel all of "
            "your strength and resolve being sapped from your body.\n"
            "\n");

   add_item(({"sweat"}),
            "   Sweat runs down your back and off your brow in rivers.  The "
            "heat cuts through your clothes without mercy and hammers the "
            "strength from your body.  Your clothes seem to remain dry as "
            "every drop of water evaporates the instant the cloth absorbs it."
            "\n\n");

  set_god_here("ducky");
   add_exit("north", "/d/sf/areas/roads/of_road/ssroad12.c", "path");
} /* setup */
