#define SAVANNAH "/d/newbie/half-elf/rooms/savannah/"
#define JUNGLE "/d/newbie/half-elf/rooms/jungle/"
#define SECRET "/d/newbie/half-elf/rooms/secret/"
#define CAST   "/d/newbie/half-elf/rooms/castle/"
#define ITEMS  "/d/newbie/half-elf/items/"
#define DROW   "/d/newbie/half-elf/rooms/drows/"
#define NPC "/d/newbie/half-elf/npcs/"
#define TOWN  "/d/newbie/half-elf/rooms/town/"
