#define WEAP "/d/newbie/duergar/weapons/"
#define BUILD "/d/bf/banefall/dendall/buildings/"
#define DNPC "/d/newbie/duergar/npcs/"
#define ITEMS "/d/newbie/duergar/items/"
#define NEWBIE "/d/newbie/duergar/rooms/"
