#define SHIELDCITY "players"
#define IM1A "a dark, yet very stout looking keep entrance"
#define IM1B "a modest looking two story mansion"
#define IR1A "/w/aginor/workroom"
#define IR1B "/w/choett/workroom"
#define IM2A "a shadowy palace, the entrance of which is just darkness"
#define IM2B "a waterfall, cascading from the air itself, it looks as if there is a room beyond it"
#define IR2A "/w/devir/workroom"
#define IR2B "/w/donald/workroom"
#define IM3A "a powerful looking castle made of black marble"
#define IM3B "a red portal"
#define IR3A "/w/gloriana/workroom"
#define IR3B "/w/grimbrand/workroom"
#define IM4A "a blue swirling portal"
#define IM4B "a stout medieval keep"
#define IR4A "/w/jedi/workroom"
#define IR4B "/w/kaelrin/workroom"
#define IM5A "what appears to be a large white marble courthouse"
#define IM5B "a battle outpost"
#define IR5A "/w/kelaronus/workroom"
#define IR5B "/w/moradin/workroom"
#define IM6A "a magical garden, with a small palace in the center of it."
#define IM6B "a swirling portal"
#define IR6A "/w/morgana/workroom"
#define IR6B "/w/parsion/workroom"
#define IM7A "a portal flashing with lightning"
#define IM7B "a building with a door that has a sign that reads 'restroom' above it"
#define IR7A "/w/raiden/workroom"
#define IR7B "/w/sheehan/workroom"
#define IM8A "the west side of the square"
#define IM8B "the east side of the square"
#define IR8A ""
#define IR8B ""
#define IM9A "a statue of a dragon"
#define IM9B "a statue of a large bird"
#define IR9A ""
#define IR9B ""
#define IM10A "the west side of the square"
#define IM10B "the east side of the square"
#define IR10A 
#define IR10B 
#define IM11A "a narrow shadowy alley"
#define IM11B "a portal flashing with lightning"
#define IR11A "/w/simkin/workroom"
#define IR11B "/w/raiden/workroom"
#define IM12A "a stone keep"
#define IM12B "a statue of a large humanoid"
#define IR12A "/w/swordmaster/workroom"
#define IR12B ""
#define IM13A "a large forest"
#define IM13B "a twisted palace, black and gloomy"
#define IR13A "/w/tahn/workroom"
#define IR13B "/w/taliesin/workroom"
#define IM14A "a building with a door that has a sign that reads 'restroom' above it"
#define IM14B "a fiery portal"
#define IR14A "/w/sheehan/workroom"
#define IR14B "/w/sojan/workroom"
#define IM15A "a large humanoid like statue"
#define IM15B "a portal flashing with rainbow colors"
#define IR15A ""
#define IR15B "/w/virga/workroom"
#define IM16A "a magnificient ruby keep"
#define IM16B "a white glowing portal"
#define IR16A "/w/wrath/workroom"
#define IR16B "/w/zanzabar/workroom"
